config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'search', to: 'projects#search', as: :search

  resources :projects, except: %i[edit update destroy] do
    resources :contracts, only: %i[new create]
  end
  resources :contracts, only: %i[index show]
  resources :favorites, only: %i[index destroy create]
  get 'contracts/:id/send_facturation', to: 'contracts#send_facturation', as: :send_facturation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :user
  belongs_to :project

  after_save do |contract|
    contract.project.compute_investment
  end

  validates :investment, presence: true, numericality: { only_integer: true }

  def perc_investment
    investment.fdiv(project.investment_cap)
  end

  def uhi
    perc_investment * project.uhi
  end

  def water_infiltration
    perc_investment * project.water_infiltration
  end

  def biodiversity
    perc_investment * project.biodiversity
  end

  def local_food
    perc_investment * project.local_food
  end

  def format_currency
    self.investment.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1 ').reverse
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :contracts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  has_one_attached :photo

  reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo = results.first
      obj.city = geo.city
    end
  end
  after_validation :reverse_geocode

  validates :surface, presence: true, numericality: { only_integer: true }, allow_blank: false
  validates :investment_cap, presence: true, numericality: { only_integer: true }, allow_blank: false
  validates :duration, presence: true, numericality: { only_integer: true }, allow_blank: false
  validates :uhi, presence: true, numericality: { only_integer: true }
  validates :biodiversity, presence: true, numericality: { only_integer: true }
  validates :water_infiltration, presence: true, numericality: { only_integer: true }
  validates :local_food, presence: true, numericality: { only_integer: true }
  validates :start_date, presence: true, allow_blank: false
  validates :name, presence: true, allow_blank: false, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 30 }
  validate :type_in_list?

  def compute_investment
    investment = contracts.reduce(0) { |sum, contract| sum + contract.investment }
    update(investment: investment)
  end

  def liked_by_current_user?(current_user)
    favorites.find_by(project: self, user: current_user).present?
  end

  def format_currency
    self.investment_cap.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1 ').reverse
  end

  def format_total_investment
    self.investment.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1 ').reverse
  end

  private

  def type_in_list?
    project_types = ['agriculture', 'forest', 'haies']
    unless project_type && project_types.include?(project_type)
      errors.add(:project_type, 'must be in the list of defined projects type')
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy
  has_many :contracts, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: %i[show send_facturation]
  before_action :set_project, only: %i[new create]

  def index
    @contracts = Contract.all
  end

  def show
    @perc = @contract.perc_investment
    @uhi = @contract.uhi
    @water_infiltration = @contract.water_infiltration
    @biodiversity = @contract.biodiversity
    @local_food = @contract.local_food
  end

  def new
    @contract = Contract.new
    @marker = {
      lat: @project.latitude,
      lng: @project.longitude
    }
  end

  def create
    @contract = Contract.new(contract_params)
    @contract.project = @project
    @contract.user = current_user
    @contract.status = 'Invoice sent'
    @contract.save
    redirect_to contract_path(@contract)
  end

  def send_facturation
    UserMailer.with(user: current_user, contract: @contract).facturation.deliver_now
    redirect_to project_path(@contract.project)
  end


  private

  def set_contract
    @contract = Contract.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def contract_params
    params.require(:contract).permit(:investment)
  end

  # def perc_investment
  #   @perc = @contract.investment.fdiv(@contract.project.investment_cap)
  # end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = Favorite.where(user: current_user)
  end

  def create
    @user = current_user
    @project = Project.find(params[:favorite][:project])
    @favorite = Favorite.new(user: current_user, project: @project)
    @favorite.save
    render :create
  end

  def destroy
    @user = current_user
    @project = Project.find(params[:favorite][:project])
    @favorite = Favorite.find_by(user: current_user, project: @project)
    @favorite.destroy
    render :create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update]
  skip_before_action :authenticate_user!, only: %i[search show]

  def index
    @projects = Project.all
  end

  def search
    @projects = Project.near(params[:q], 30)
    @markers = @projects.map do |project|
      {
        lat: project.latitude,
        lng: project.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { project: project })
      }
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @project.uhi = compute_bonus
    @project.biodiversity = compute_bonus
    @project.water_infiltration = compute_bonus
    @project.local_food = compute_bonus
    raise
    @project.save
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name,
                                    :description,
                                    :investment_cap,
                                    :duration, :surface,
                                    :start_date,
                                    :project_type,
                                    :latitude,
                                    :longitude,
                                    :photo)
  end

  def compute_bonus
    return 0
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contracts/index.html.erb
<% @contracts.each do |contract| %>
  <%= link_to contract_path(contract) do %>
    <%= contract.project.name %><br>
    <%= contract.project.duration %><br>
    <%= contract.investment %><br>
    <%= contract.status %><br>
    <br>
  <% end %>
<% end %>

app/views/contracts/new.html.erb
<div class="container-fluid">
  <h1 class="result-title text-center mb-4"><%= @project.name %></h1>
    <div class="row d-flex justify-content-around my-4">
      <div class="col-4 d-flex flex-column">
        <div class="variable-impact d-flex flex-column mb-4">
          <div class="impact-top d-flex justify-content-between">
            <div class="imp-box border border-primary rounded text-center m-2 p-2">
              <h4>-<span class="impact-calculation" data-value="<%= @project.uhi %>"><%= @project.uhi %></span>°C</h4>
              <h5>Chaleur Urbaine</h5>
            </div>
            <div class="imp-box border border-primary rounded text-center m-2 p-2">
              <h4><span class="impact-calculation" data-value="<%= @project.water_infiltration %>"><%= @project.water_infiltration %></span>m³</h4>
              <h5>Infiltration d'eau</h5>
            </div>
          </div>
          <div class="impact-bottom d-flex justify-content-between">
            <div class="imp-box border border-primary rounded text-center m-2 p-2">
              <h4><span class="impact-calculation" data-value="<%= @project.biodiversity %>"><%= @project.biodiversity %></span></h4>
              <h5>Biodiversité</h5>
            </div>
            <div class="imp-box border border-primary rounded text-center m-2 p-2">
              <h4><span class="impact-calculation" data-value="<%= @project.local_food %>"><%= @project.local_food %></span>%</h4>
              <h5>Nourriture Locale</h5>
            </div>
          </div>
      </div>
        <div class="inv-input mt-4">
          <%= simple_form_for [@project, @contract] do |f| %>
            <%= f.input :investment, label: "Montant de votre investissement - €" %>
            <input  type="range"
                    id="investRange"
                    class="custom-range"
                    name="investRange"
                    min="0"
                    max="100"
                    value="0"
                    step="1"
                    data-cap="<%= @project.investment_cap %>">
            <div class="d-flex justify-content-center my-4">
              <%= f.submit "Je finance", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
      <div
        class="col-6"
        id="investProjectMap"
        style="width: 100%; height: 80vh;"
        data-marker="<%= @marker.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
  </div>
</div>


<!-- <div class="page-grid d-flex flex-column border border-beige p-4 rounded"> -->

app/views/contracts/show.html.erb
<!-- <div>
<%= @contract.project.name %><br>
<%= @contract.project.duration %><br>
<%= @contract.investment %><br>
<%= @contract.status %><br>
</div> -->
<div class="row mt-4 d-flex justify-content-center">
  <div class="col-8">
    <%= render 'shared/contract_card', contract: @contract %>
  </div>
</div>

app/views/favorites/_horizontal_card.html.erb
<tr class="text-center align-middle">
  <td align="left">
    <i class="fas fa-grip-lines text-secondary"></i>
    <a data-toggle="collapse" data-target="#collapseProject<%= project.id %>">
      <%= project.name %>
    </a>
  </td>
  <td><p>-<%= project.uhi %>°C</p></td>
  <td><p><%= project.water_infiltration %>m³</p></td>
  <td><p><%= project.biodiversity %></p></td>
  <td><p><%= project.local_food %>%</p></td>
</tr>

app/views/favorites/create.js.erb
function refreshForm(innerHTML) {
  const newLikeForm = document.getElementById('like-project-<%=@project.id%>');
  newLikeForm.innerHTML = innerHTML;
}

function updateFavCount() {
   const badge = document.querySelector('.badge');
   badge.innerHTML = <%= current_user.favorites.count %>;
}


refreshForm('<%= j render "shared/like_unlike", project: @project, user: @user %>');
updateFavorite();
updateFavCount();

app/views/favorites/destroy.js.erb
console.log('destroying');

app/views/favorites/index.html.erb
<div class="container">
  <div class="accordion" id="accordionProjects">
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="border-top-0"></th>
          <th class="border-top-0"><p class="sort-title text-primary"><i class="sort-icon fas fa-sort text-light mx-1"></i>Chaleur Urbaine</p></th>
          <th class="border-top-0"><p class="sort-title text-primary"><i class="sort-icon fas fa-sort text-light mx-1"></i>Infiltration</p></th>
          <th class="border-top-0"><p class="sort-title text-primary"><i class="sort-icon fas fa-sort text-light mx-1"></i>Biodiversité</p></th>
          <th class="border-top-0"><p class="sort-title text-primary"><i class="sort-icon fas fa-sort text-light mx-1"></i>Nourriture locale</p></th>
        </tr>
      </thead>
      <tbody>
        <% @favorites.each do |fav| %>
          <%= render 'horizontal_card', project: fav.project %>
        <% end %>
      </tbody>
    </table>
    <% @favorites.each do |fav| %>
        <div id="collapseProject<%= fav.project.id %>" class="collapse" data-parent="#accordionProjects">
            <div class="row m-2">
              <div class="col-7">
                <%= render 'shared/left_project_card', project: fav.project %>
              </div>
              <div class="col-5">
                <%= render 'shared/right_project_card', project: fav.project %>
              </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag  %>
    <!-- <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" sizes="96x96" href="favicon-96.png" type="image/png" -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta property="og:title" content="Humus Eco-Projets in France" />
    <meta property="og:description" content="Investissez dans les éco-projets Humus pour que la campagne reste verte." />
    <meta property="og:type" content="ecology projects" />
    <meta property="og:url" content="https://humus-eco.herokuapp.com" />
    <meta property="og:image" content="https://humus-eco.herokuapp.com/banner_og.jpg"/>


    <title>Humus Eco-Projets in France</title>
    <meta name="description" content="Investissez dans les éco-projets Humus pour que la campagne reste verte.">
    <Meta name="keywords" content="biodiversité, écologie, éco-projets, developement durable, urbanisme" >
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/humus_navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="background-home-image d-flex flex-column justify-content-center text-center">
  <h1>Investissez dans votre ville</h1>
  <h2>Améliorez le quotidien de vos riverains</h2>
</div>

<div class="container mt-n5">
  <%= render 'shared/search_bar' %>
  <div class="my-container justify-content-around d-flex flex-wrap mt-5">
    <div class = "my-5">
      <%= render 'shared/card', project: @projects.first %>
    </div>
    <div class = "my-5">
      <%= render 'shared/card', project: @projects.last %>
    </div>
    <div class = "my-5">
      <%= render 'shared/card', project: @projects.second %>
    </div>
    <div class = "my-5">
      <%= render 'shared/card', project: @projects.third %>
    </div>
  </div>
</div>
  <div class = "d-flex justify-content-center mb-5">
    <button class="btn btn-primary">Tous nos projets</button>
  </div>

<div class = "secondary-background py-4">
  <div class="concept-title text-center d-flex flex-column justify-content-center">
    <h2>Concept</h2>
  </div>
    <div class = "container">
      <div class = "concept-parts d-flex justify-content-around">
        <div class= "col-2 text-center">
          <%= image_tag "01_decouvrez.jpg" %>
          <h6>Découvrez les projets autour de vous</h6>
        </div>
        <div class= "col-2 text-center">
          <%= image_tag "02_investissez.png" %>
          <h6>Investissez dans vos projets favoris</h6>
        </div>
        <div class= "col-2 text-center">
          <%= image_tag "03_suivez.png" %>
          <h6>Suivez vos investissements</h6>
        </div>
        <div class= "col-2 text-center">
          <%= image_tag "04_recevez_benefices.png" %>
          <h6>Recevez le calcul de votre impact</h6>
        </div>
      </div>
    </div>
</div>

<div class="impact d-flex flex-column justify-content-center">
  <div class="container d-flex justify-content-around text-center">
    <div class= "elemental-impact d-flex flex-column justify-content-center">
      <h2>1047</h2>
      <h4>Projets financés</h4>
    </div>
    <div class= "elemental-impact d-flex flex-column justify-content-center">
      <h2>683</h2>
    <h4>Villes impactées</h4>
    </div>
    <div class= "elemental-impact d-flex flex-column justify-content-center">
      <h2>16m€</h2>
    <h4>collectés</h4>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/projects/_info_window.html.erb
<%= link_to project.name, project_path(project) %>

app/views/projects/index.html.erb
<h1 class="text-center text-primary my-5">Vos projets favoris</h1>
<div class="d-flex justify-content-around flex-wrap">
  <% @projects.each do |project| %>
    <% if project.liked_by_current_user?(current_user) %>
      <div class="container">
        <div class = "my-5">
          <%= render 'shared/card', project: project %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/projects/new.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :investment_cap %>
  <%= f.input :surface %>
  <%= f.input :start_date %>
  <%= f.input :duration %>
  <%= f.input :project_type, collection: ['agriculture', 'forest'] %>
  <%= f.input :photo, as: :file %>

  <%= f.input :longitude, as: :hidden %>
  <%= f.input :latitude, as: :hidden %>
  <%= f.button :submit %> <%= link_to "Submit", "#", class: "btn btn-primary text-center" %>
<% end %>

<div
  id="createProjectMap"
  style="width: 100%;
  height: 600px;"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/projects/search.html.erb
<div class="container-fluid pr-0">
  <div class="col-12 m-2 text-primary text-center">
    <h1>Tous les projets à <%= params[:q].split(',').first %></h1>
  </div>
  <div class="row ml-2">
    <div class="col-6">
        <% @projects.each do |project| %>
        <%= render 'shared/card', project: project %>
        <% end %>
    </div>
    <div class="col-6">
      <div class="sticky-top pt-2">
        <div
          id="searchProjectMap"
          style="width: 100%; height: 600px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container-fluid">
  <div class="col-12 m-2 text-primary">
    <h1><%= @project.name %></h1>
  </div>
  <div class="row m-2">
    <div class="col-8">
      <%= render 'shared/left_project_card', project: @project %>
    </div>
    <div class="col-4">
      <%= render 'shared/right_project_card', project: @project %>
    </div>
  </div>
</div>

app/views/shared/_contract_card.html.erb
<div class="container">
  <div class="contract-card d-flex flex-column border border-beige p-4 rounded">
    <div class="box-top">
      <h1><%= contract.project.name %></h1>
      <div class="container pb-4 pt-4">
        <div class="row">
          <div class="col text-left"><h4>Votre donation</h4></div>
          <div class="col text-right text-primary pr-4"><h4><%= contract.format_currency %>€</h4></div>
          <div class="col text-left pl-4"><h4>Votre Apport</h4></div>
          <div class="col text-right text-primary"><h4><%= (@perc * 100).round  %>%</h4></div>
        </div>
        <div class="row">
          <div class="col text-left"><h4>Debut Projet</h4></div>
          <div class="col text-right text-primary pr-4"><h4><%= Date.today %></h4></div>
          <div class="col text-left pl-4"><h4>Durée Projet</h4></div>
          <div class="col text-right text-primary"><h4><%= contract.project.duration %> ans</h4></div>
        </div>
      </div>
    </div>
    <div class="box-middle border-top border-beige pt-4">
      <h2>Votre Contribution écologique</h2>
      <div class="eco-contribution pb-4 pt-2 d-flex justify-content-between">
        <div class="eco-result-box border border-primary rounded text-center">
          <div class="first-row mt-2 pt-2">
            <h3>-<%= (@uhi).round(1) %>°C</h3>
          </div>
          <div class="second-row mb-2 pb-2">
            <h5>Chaleur Urbaine</h5>
          </div>
        </div>
        <div class="eco-result-box border border-primary rounded text-center">
          <div class="first-row mt-2 pt-2">
            <h3><%= (@water_infiltration).round(1) %>m³</h3>
          </div>
          <div class="second-row mb-2 pb-2">
            <h5>Infiltration d'eau</h5>
          </div>
        </div>
        <div class="eco-result-box border border-primary rounded text-center">
          <div class="first-row mt-2 pt-2">
            <h3><%= (@biodiversity).round(1) %></h3>
          </div>
          <div class="second-row mb-2 pb-2">
            <h5>Biodiversité</h5>
          </div>
        </div>
        <div class="eco-result-box border border-primary rounded text-center">
          <div class="first-row mt-2 pt-2">
            <h3><%= (@local_food).round(1) %>%</h3>
          </div>
          <div class="second-row mb-2 pb-2">
            <h5>Nourriture Locale</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="box-bottom d-flex justify-content-center">
      <button id="invoice-send" class="btn btn-primary">Envoyer la facture</button>
      <%= link_to "", send_facturation_path(contract), class: "hidden", id: "email-confirmation" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer d-flex justify-content-center">
  <div class="d-flex align-items-center">
    <a href="">Presse</a>
    <a href="">A propos</a>
    <a href="">Contact</a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</footer>

app/views/shared/_humus_navbar.html.erb
<div class="humus-navbar d-flex justify-content-between align-items-center py-2">
  <div class="left d-flex align-items-center ml-4">

    <%= link_to root_path do %>
      <%= image_tag "planet_logo.png" %>
    <% end %>
    <%= link_to "Mes Projets Favoris", favorites_path, class: "nav-item nav-link" %>
    <% if current_user.present? %>
      <span class="badge badge-primary"><%= current_user.favorites.count %></span>
    <% end %>
    <!-- <a class="nav-item nav-link" href="projects">Projets</a> -->
    <!-- <a class="nav-item nav-link" href="#">Concept</a> -->
  </div>
  <div class="right mr-4">
    <% if current_user %>
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link" %>
    <% else %>
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
    <% end %>
    <!-- <a class="nav-item nav-link" href="#">Profile</a> -->
  </div>
</div>

app/views/shared/_like_unlike.html.erb
<% if project.liked_by_current_user?(user) %>
  <i class="fas fa-star fa-lg fav-star-pos text-info" data-projectid="<%= project.id %>" style="z-index: 1020; display: inline"></i>
  <%= simple_form_for(Favorite.new, url: favorite_path(project), method: :delete, remote: true) do |f| %>
    <%= f.submit :style => "display: none;" %>
    <%= f.input :project, :as => :hidden, :input_html => { :value => project.id } %>
  <% end %>
<% else %>
  <i class="far fa-star fa-lg fav-star-pos text-info" data-projectid="<%= project.id %>" style="z-index: 1020; display: inline"></i>
  <%= simple_form_for(Favorite.new, url: favorites_path, method: :post, remote: true) do |f| %>
    <%= f.submit :style => "display: none;" %>
    <%= f.input :project, :as => :hidden, :input_html => { :value => project.id } %>
  <% end %>
<% end %>

app/views/shared/_right_project_card.html.erb
<div class="card-box d-flex flex-column border border-beige p-4 rounded">
  <div class="top-box ml-2 mr-2">
    <div class="money mb-2">
      <div class="money-collected d-flex justify-content-between">
        <div class="left">
          <h4><b>Montant collecté</b></h4>
        </div>
        <div class="right">
          <h4><%= project.format_total_investment %>€</h4>
        </div>
      </div>
      <div class="money-total d-flex justify-content-between align-items-center">
        <div class="progress flex-grow-1 mr-4" style="height: 12px;">
          <div class="progress-bar"
               role="progressbar"
               style="width: <%=  project.investment.fdiv(project.investment_cap) * 100 %>%"
               aria-valuenow="<%=  project.investment.fdiv(project.investment_cap) * 100 %>"
               aria-valuemin="0"
               aria-valuemax="100">
          </div>
        </div>
        <div class="right">
          <h4><%= project.format_currency %>€</h4>
        </div>
      </div>
    </div>
    <div class="info mb-2">
      <div class="days-left d-flex justify-content-between">
        <div class="left">
          <h5>Jour(s) restant(s)</h5>
        </div>
        <div class="right">
          <h5><%= (project.start_date - Date.today).to_i %></h5>
        </div>
      </div>
      <div class="investors d-flex justify-content-between mb-3">
        <div class="left">
          <h5>Nombre de prêteurs</h5>
        </div>
        <div class="right">
          <h5><%= project.contracts.length %></h5>
        </div>
      </div>
    </div>
  </div>
  <div class="middle-box border-top border-beige">
    <div class="results">
      <div class="top-results d-flex justify-content-between mt-4">
        <div class="impact-box border border-primary ml-2 rounded text-center p-2">
          <div class="first-row">
            -<%=  project.uhi %>°C
          </div>
          <p data-toggle="tooltip" title="Si tout le monde faisait comme vous, la température en ville baisserait de <%= project.uhi %>°C.">
            Chaleur Urbaine<br><i class="far fa-question-circle"></i>
          </p>
        </div>
        <div class="impact-box border border-primary mr-2 rounded text-center p-2">
          <div class="first-row">
            <%=  project.water_infiltration %>m³
          </div>
          <p>
            <p data-toggle="tooltip" title="Tant qu'il pleut moins que ce volume, il n'y a pas de rejet vers la ville.">
            Infiltration d'eau<br><i class="far fa-question-circle"></i>
          </p>
        </div>
      </div>
      <div class="bottom-results d-flex justify-content-between mt-2">
        <div class="impact-box border border-primary ml-2 rounded text-center p-2">
          <div class="first-row">
            <%=  project.biodiversity %>
          </div>
          <p>
            <p data-toggle="tooltip" title="Mesure à la fois le nombre d'individu et la diversité de leur espèces (5 renards < 10 renards < 5 renards + 5 chouettes)">
            Biodiversité<br><i class="far fa-question-circle"></i>
          </p>
        </div>
        <div class="impact-box border border-primary mr-2 rounded text-center p-2">
          <div class="first-row">
            <p data-toggle="tooltip" title="Pourcentage de nourriture locale. 100% designe l'autosuffisance.">
            <%=  project.local_food %>%
          </div>
          <p>
            Nourriture Locale<br><i class="far fa-question-circle"></i>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="bottom-box d-flex justify-content-center mt-4">
    <%= link_to "Je finance", new_project_contract_path(project), class: "btn btn-primary" %>
  </div>

</div>